# config.yaml

run_mode: auto    # manual, range or auto
start_date: "2024-02-01"  # your start date
end_date: "2024-02-10"    # ignore if auto

period: monthly             # options: daily, weekly, monthly
onward_period: 0          # how many +1 periods to run starting from start_date
backward_period: 1          # how many periods to run starting from start_date

discord_webhook_url: "https://discord.com/api/webhooks/URL"
